ALTER TABLE mailbot CHANGE mail_status mail_status VARCHAR(255) NOT NULL, CHANGE fehler fehler VARCHAR(300) DEFAULT NULL;
ALTER TABLE freilose DROP FOREIGN KEY freilose_ibfk_2;
ALTER TABLE freilose DROP FOREIGN KEY freilose_ibfk_1;
ALTER TABLE freilose CHANGE gesetzt_am gesetzt_am DATETIME DEFAULT 'current_timestamp(1)', CHANGE erstellt_am erstellt_am DATETIME DEFAULT 'current_timestamp(1)' NOT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE grund grund VARCHAR(255) NOT NULL;
ALTER TABLE freilose ADD CONSTRAINT FK_CFFB47C6296CD8AE FOREIGN KEY (team_id) REFERENCES teams_liga (team_id);
ALTER TABLE freilose ADD CONSTRAINT FK_CFFB47C6B5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
CREATE UNIQUE INDEX UNIQ_CFFB47C6B5FFB8C1 ON freilose (turnier_id);
ALTER TABLE teams_kontakt DROP FOREIGN KEY teams_kontakt_ibfk_1;
ALTER TABLE teams_kontakt CHANGE team_id team_id INT DEFAULT NULL, CHANGE public public VARCHAR(0) DEFAULT 'Ja' NOT NULL, CHANGE get_info_mail get_info_mail VARCHAR(0) DEFAULT 'Ja' NOT NULL;
ALTER TABLE teams_kontakt ADD CONSTRAINT FK_1F9B6EE3296CD8AE FOREIGN KEY (team_id) REFERENCES teams_liga (team_id);
ALTER TABLE teams_kontakt RENAME INDEX team_id TO IDX_1F9B6EE3296CD8AE;
DROP INDEX teamname ON teams_liga;
ALTER TABLE teams_liga CHANGE ligateam ligateam VARCHAR(0) DEFAULT 'Ja' NOT NULL, CHANGE terminplaner terminplaner VARCHAR(0) DEFAULT 'Nein' NOT NULL, CHANGE passwort_geaendert passwort_geaendert VARCHAR(0) DEFAULT 'Nein' NOT NULL, CHANGE aktiv aktiv VARCHAR(0) DEFAULT 'Ja' NOT NULL;
ALTER TABLE teams_liga ADD CONSTRAINT FK_EDF637B0296CD8AE FOREIGN KEY (team_id) REFERENCES teams_details (team_id);
ALTER TABLE spieler DROP FOREIGN KEY spieler_ibfk_1;
ALTER TABLE spieler CHANGE geschlecht geschlecht VARCHAR(0) NOT NULL, CHANGE junior junior VARCHAR(0) DEFAULT NULL;
ALTER TABLE spieler ADD CONSTRAINT FK_3458B7B2296CD8AE FOREIGN KEY (team_id) REFERENCES teams_liga (team_id);
ALTER TABLE spieler RENAME INDEX team_id TO IDX_3458B7B2296CD8AE;
ALTER TABLE teams_details DROP FOREIGN KEY teams_details_ibfk_1;
DROP INDEX team_id ON teams_details;
ALTER TABLE teams_details ADD PRIMARY KEY (team_id);
ALTER TABLE turniere_liga DROP tblock_fixed, CHANGE art art VARCHAR(0) DEFAULT NULL, CHANGE datum datum DATE NOT NULL, CHANGE spieltag spieltag INT DEFAULT NULL, CHANGE phase phase VARCHAR(255) DEFAULT NULL, CHANGE sofort_oeffnen sofort_oeffnen TINYINT(1) NOT NULL, CHANGE canceled canceled TINYINT(1) NOT NULL, CHANGE erstellt_am erstellt_am DATETIME NOT NULL;
ALTER TABLE turniere_liga RENAME INDEX spielplan_vorlage TO IDX_7709F3EEB533C0D;
ALTER TABLE turniere_liga RENAME INDEX ausrichter_team_id TO IDX_7709F3EEC431154E;
ALTER TABLE turniere_berichte DROP INDEX turnier_id, ADD UNIQUE INDEX UNIQ_175830B7B5FFB8C1 (turnier_id);
ALTER TABLE turniere_berichte DROP FOREIGN KEY turniere_berichte_ibfk_1;
ALTER TABLE turniere_berichte CHANGE bericht_id bericht_id INT NOT NULL, CHANGE kader_ueberprueft kader_ueberprueft VARCHAR(0) NOT NULL;
ALTER TABLE turniere_berichte ADD CONSTRAINT FK_175830B7B5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
ALTER TABLE turniere_details DROP FOREIGN KEY turniere_details_ibfk_1;
ALTER TABLE turniere_details CHANGE plz plz VARCHAR(6) NOT NULL, CHANGE startzeit startzeit TIME NOT NULL, CHANGE besprechung besprechung VARCHAR(0) DEFAULT NULL;
ALTER TABLE turniere_details ADD CONSTRAINT FK_3E5FB9D9B5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
ALTER TABLE turniere_liste DROP FOREIGN KEY turniere_liste_ibfk_1;
ALTER TABLE turniere_liste DROP FOREIGN KEY turniere_liste_ibfk_2;
ALTER TABLE turniere_liste CHANGE turnier_id turnier_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE liste liste VARCHAR(0) DEFAULT 'setz' NOT NULL, CHANGE freilos_gesetzt freilos_gesetzt VARCHAR(0) DEFAULT 'Nein' NOT NULL, CHANGE freilos_gesetzt_am freilos_gesetzt_am DATETIME DEFAULT 'current_timestamp(1)' NOT NULL;
ALTER TABLE turniere_liste ADD CONSTRAINT FK_8485516E296CD8AE FOREIGN KEY (team_id) REFERENCES teams_liga (team_id);
ALTER TABLE turniere_liste ADD CONSTRAINT FK_8485516EB5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
ALTER TABLE turniere_liste RENAME INDEX turniere_liste_ibfk_1 TO IDX_8485516E296CD8AE;
ALTER TABLE turniere_liste RENAME INDEX turniere_liste_ibfk_2 TO IDX_8485516EB5FFB8C1;
ALTER TABLE turniere_log ADD CONSTRAINT FK_57F3AFC0B5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
ALTER TABLE turniere_log RENAME INDEX turnier_id TO IDX_57F3AFC0B5FFB8C1;
ALTER TABLE turniere_ergebnisse DROP INDEX team_id, ADD UNIQUE INDEX UNIQ_D20CA5E9296CD8AE (team_id);
ALTER TABLE turniere_ergebnisse DROP FOREIGN KEY turniere_ergebnisse_ibfk_1;
ALTER TABLE turniere_ergebnisse DROP FOREIGN KEY turniere_ergebnisse_ibfk_2;
ALTER TABLE turniere_ergebnisse CHANGE team_id team_id INT DEFAULT NULL, CHANGE turnier_id turnier_id INT DEFAULT NULL;
ALTER TABLE turniere_ergebnisse ADD CONSTRAINT FK_D20CA5E9296CD8AE FOREIGN KEY (team_id) REFERENCES teams_liga (team_id);
ALTER TABLE turniere_ergebnisse ADD CONSTRAINT FK_D20CA5E9B5FFB8C1 FOREIGN KEY (turnier_id) REFERENCES turniere_liga (turnier_id);
ALTER TABLE turniere_ergebnisse RENAME INDEX turniere_ergebnisse_ibfk_2 TO IDX_D20CA5E9B5FFB8C1;
