version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ..:/workspace
    environment:
      PHP_POST_MAX_SIZE: 20M
      PHP_UPLOAD_MAX_FILESIZE: 20M
  db:
    image: mariadb:12.2.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_localhost
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
    volumes:
      - db-data:/var/lib/mysql
      - ../_localhost/db_localhost.sql:/docker-entrypoint-initdb.d/db_localhost.sql:ro
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:5.2.3
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      PMA_USER: appuser
      PMA_PASSWORD: apppass
      UPLOAD_LIMIT: 256M
    depends_on:
    - db

volumes:
  db-data:
